twig:
    paths: 
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/public/images'
    form_themes:
        # - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_5_layout.html.twig'
    globals:
        # APP_VERSION: '%env(APP_VERSION)%'

when@test:
    twig:
        strict_variables: true
